"""Initial DB schema

Revision ID: 539e78ad85d5
Revises: 5979098b5093
Create Date: 2025-07-31 22:58:30.287999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539e78ad85d5'
down_revision: Union[str, Sequence[str], None] = '5979098b5093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['order_number'])
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('rental_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'products', ['sku'])
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'rental_price')
    op.drop_column('products', 'category')
    op.drop_column('products', 'sku')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'comments')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'payment_status')
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
