"""Add email and passsword in Tenant

Revision ID: 774f8b16e6a6
Revises: 9c7bba014d9b
Create Date: 2025-08-28 17:39:29.263812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774f8b16e6a6'
down_revision: Union[str, Sequence[str], None] = '9c7bba014d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
