"""Add customer id & tenant id In Rental

Revision ID: de5be9ac18d5
Revises: 774f8b16e6a6
Create Date: 2025-08-29 14:24:14.791768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5be9ac18d5'
down_revision: Union[str, Sequence[str], None] = '774f8b16e6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('rentals', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rentals_customer_id'), 'rentals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rentals_tenant_id'), 'rentals', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'rentals', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'rentals', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_index(op.f('ix_rentals_tenant_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_customer_id'), table_name='rentals')
    op.drop_column('rentals', 'customer_id')
    op.drop_column('rentals', 'tenant_id')
    # ### end Alembic commands ###
